---
- name: Install Java and Maven
  hosts: webservers
  become: yes
  tasks:

    - name: Install Java (OpenJDK 11)
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Verify Java installation
      command: java -version
      register: java_version
      ignore_errors: yes

    - name: Display Java version
      debug:
        msg: "Java version installed: {{ java_version.stdout }}"

    - name: Install Maven
      apt:
        name: maven
        state: present

    - name: Verify Maven installation
      command: mvn -v
      register: maven_version
      ignore_errors: yes

    - name: Display Maven version
      debug:
        msg: "Maven version installed: {{ maven_version.stdout }}"
